movies = int(input('Each week, how many hours do you spend watching movies? '))
tv = int(input('Each week, how many hours do you spend watching TV? '))
books = int(input('Each week, how many hours do you spend reading books for fun? '))
art = int(input('Each week, how many hours do you spend on your own artistic expressions? '))
stars = int(input('Each week, how many hours do you spend watching thinking about Star Wars or Star Trek? '))
print('OK, Here is a text-based graph of your survey responses')
print('MOVIES', movies)
print('TV', tv)
print('READING', books)
print('ART', art)
print('SW/ST', stars)